#!/bin/bash

/etc/init.d/bind9 start

named-checkzone -i full tocinitos.com /etc/bind/db.tocinitos
named-checkzone -i full 185.143.168.192.in-addr.arpa /etc/bind/db.172
named-checkzone -i full 6.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa /etc/bind/db.2001
named-checkconf -z

echo "nameserver $(hostname -I)" >> /etc/resolv.conf
/etc/init.d/bind9 start
tcpdump -i lo port 80
